
    Vagrant.configure('2') do |config|
    config.vm.box = 'jesuisunebox'
    config.vm.hostname = 'jesuisunebox'
    config.vm.define "jesuisunebox"
    config.winrm.timeout = 1800
    config.vm.boot_timeout = 1800
    config.vm.provider "vmware_workstation" do |v|
      v.gui = false
      v.vmx["memsize"] = "512"
      v.vmx["numvcpus"] = "1"
      v.vmx["cpuid.coresPerSocket"] = "1"
    end
  end
    